name: Git Diff

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  git-diff:
    name: "Git Diff Branches"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Run Git Diff Branches
        run: |
          echo BASE_REF:
          echo ${{ github.base_ref }}
          echo HEAD_REF:
          echo ${{ github.head_ref }}

          FILES_TO_DEPLOY="$(git diff --name-only --diff-filter=d origin/${{github.base_ref}}..origin/${{github.head_ref}} | grep -F src | sed '$!s/$/,/' | xargs)"

          echo FILES_TO_DEPLOY:
          echo $FILES_TO_DEPLOY

      - name: Run Git Diff Commits
        run: |
          echo COMMIT_SHA:
          echo ${{ github.sha }}

          COMMIT_SHAS="$( git log --format=format:%H -n 2 | xargs )"

          echo COMMIT_SHAS:
          echo $COMMIT_SHAS

          COMMIT_SHA_HEAD="$( echo $COMMIT_SHAS | awk '{print $1}' )"
          COMMIT_SHA_PREVIOUS="$( echo $COMMIT_SHAS | awk '{print $2}' )"
          echo COMMIT_SHA_HEAD:
          echo $COMMIT_SHA_HEAD
          echo COMMIT_SHA_PREVIOUS:
          echo $COMMIT_SHA_PREVIOUS

          FILES_TO_DEPLOY="$( git diff --name-only --diff-filter=d $COMMIT_SHA_PREVIOUS $COMMIT_SHA_HEAD | grep -F src | sed '$!s/$/,/' | xargs )"

          echo FILES_TO_DEPLOY:
          echo $FILES_TO_DEPLOY
